constraints: {
  goal_time: 0.0,
  stopped_velocity_tolerance: 0.1, 
  j2s7s300_joint_1: {
    goal: -1.0,
    trajectory: -1.0
  },
  j2s7s300_joint_2: {
    goal: -1.0,
    trajectory: -1.0
  },
  j2s7s300_joint_3: {
    goal: -1.0,
    trajectory: -1.0
  },
  j2s7s300_joint_4: {
    goal: -1.0,
    trajectory: -1.0
  },
  j2s7s300_joint_5: {
    goal: -1.0,
    trajectory: -1.0
  },
  j2s7s300_joint_6: {
    goal: -1.0,
    trajectory: -1.0
  },
  j2s7s300_joint_7: {
    goal: -1.0,
    trajectory: -1.0
  },
  j2s7s300_joint_finger_1: {
    goal: -1.0,
    trajectory: -1.0
  },
  j2s7s300_joint_finger_2: {
    goal: -1.0,
    trajectory: -1.0
  },
  j2s7s300_joint_finger_3: {
    goal: -1.0,
    trajectory: -1.0
  }
}